service: math-api
# variablesResolutionMode: 20210326

projectDir: ../../

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:service}-${self:provider.stage}

plugins: ${file(../../globalConfig.yml):plugins}

package: ${file(../../globalConfig.yml):package}

custom:
  jetpack: ${file(../../globalConfig.yml):jetpack}
  scriptHooks: ${file(../../globalConfig.yml):scriptHooks}

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: 20201221
  region: ${opt:region, 'us-east-1'}
  memorySize: 128
  versionFunctions: false
  timeout: 3

functions:
  sum:
    handler: build/sum.handler
    description: "sum"
    events:
      - http:
          path: /sum/{a}/{b}
          method: get
    layers:
      - ${cf:layers-dev.DepsLayerExport}
