service: layers

projectDir: ../

custom:
  jetpack:
  base: ".."
  concurrency: 4
  preInclude:
    - "!**"
  collapsed:
    bail: true
  scriptHook:
    after:jetpack:package:package: mv ../node_modules/.prisma

plugins:
  - serverless-jetpack
  - serverless-plugin-reducer
  - serverless-scriptable-plugin
  - serverless-offline

package:
  individually: true
  include:
    - "!**/node_modules/aws-sdk/**"
    - "!../node_modules/**/*.ts"
    - "!../node_modules/**/.serverless/**"
    - "!../node_modules/**/src/**"
    - "!**/node_modules/{@*/*,*}/*.md"
    - "build/*.js"
    - "!../node_modules/.prisma/client/libquery_engine-*"
    - "nodejs/node_modules/.prisma/client/libquery_engine-rhel-*"
    - "nodejs/node_modules/.prisma/client/index.js"
    - "nodejs/node_modules/.prisma/client/package.json"
    - "nodejs/node_modules/.prisma/client/schema.prisma"
    - "!../node_modules/prisma/libquery_engine-*"
    - "!../node_modules/@prisma/engines/**"

provider:
  name: aws

layers:
  Deps:
    path: ./
    jetpack:
      roots:
        - "./nodejs"

resources:
  Outputs:
    DepsLayerExport:
      Value:
        Ref: DepsLambdaLayer
      Export:
        Name: DepsLambdaLayer
